### TEST GET / WEBSITE
GET http://localhost:3000/

### TEST GET / DASHBAORD
GET http://localhost:3000/dashboard

### DATA ENDPOIT
GET http://localhost:3000/api/data

### DATA ENDPOINT FOR ENTERING A USER
POST http://localhost:3000/api/data
Content-Type: application/json

{
    "name": "Baap"
}

### DELETE ENDPOINT FOR DELETING A USER
DELETE http://localhost:3000/api/data/